export const BUNKER =  'bunker'
export const CAR_SHOP = 'car_shop'
export const COKE_LOCKUP = 'coke_lockup'
export const COUNTERFEIT_CASH = 'counterfeit_cash'
export const DOCUMENT_FORGERY = 'document_forgery'
export const METH_LAB= 'meth_lab'
export const WEED_FARM = 'weed_farm'
